# Cấu hình chung
namespace: kimloi

# Cấu hình ứng dụng chính
app:
  name: knautotrain
  image:
    repository: 
    tag: dev
    pullPolicy: Always
  service:
    port: 80
    targetPort: 8000
  configPath: 

# Cấu hình MongoDB
mongodb:
  image:
    repository: mongo
    tag: latest
  credentials:
    username: root
    password: 
  persistence:
    storageClass: manual
    storage: 5Gi
    hostPath: /data/mongodb

# Cấu hình Ingress
ingress:
  enabled: true
  host:
  basicAuth:
    enabled: true
    secret: my-basic-auth-secret
    credentials: 

# Cấu hình CronJob
cronjob:
  stop:
    schedule: "0 5 * * *"
    kubeconfig: /home/k8s/k3s.yaml
  start:
    schedule: "30 5 * * *"
    kubeconfig: /home/k8s/k3s.yaml 